config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post '/login', to: 'authentication#login', default: { format: :json }
      resources :users do
        get '/posts' => 'posts#index', as: :api_user_posts
        resources :posts do
          resources :comments
          post 'authenticate', to: 'authentication#create'
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts
  has_many :likes
  has_many :comments

  ROLES = %i[admin user].freeze

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def as_json(_options = {})
    super(only: [id, :name, :email, :role, :posts_counter])
  end

  def is?(requested_role)
    role == requested_role.to_s
  end

  def authenticate(password)
    valid_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    # @users = User.all
    @users = current_user

    respond_to do |format|
      format.html
      format.xml { render xml: @users }
      format.json { render json: @users }
    end
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
    @recent_posts = @user.recent_posts

    respond_to do |format|
      format.html
      format.xml { render xml: @user.posts }
      format.json { render json: @user }
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<%=render partial: 'partials/user_card', locals: { user: @users }%>

app/views/users/show.html.erb
<div class='user_body'>
  <%=render partial: 'partials/user_card', locals: { user: @user }%>
  
  <div class='bio'>
    <p>Bio</p>
    <div class='bio_text'><%=@user.bio%></div>
  </div>
  
  <div class='top_post_list'>
    <%@recent_posts.each_with_index do |post, index|%>
    <%=render partial: 'partials/post_card', locals: { post: post, index: index, user: @user }%> 
    <%end%>
    <button type='button'><%= link_to "See all posts", user_posts_path(@user) %></button>
  <div>
</div>