config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post '/login', to: 'authentication#login', default: { format: :json }
      resources :users do
        get '/posts' => 'posts#index', as: :api_user_posts
        resources :posts do
          resources :comments
          post 'authenticate', to: 'authentication#create'
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments
  belongs_to :user
  after_save :increment_user_posts_count

  validates :title, presence: true
  validates :title, length: { maximum: 250, too_long: 'The maximum characters allowed for a Title is 250 characters' }
  validates :text, presence: true, length: { maximum: 4000 }
  validates :comments_counter, comparison: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_count
    user.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
# module Api
#   module V1
#     class PostsController < ApplicationController
#       POSTS_PER_PAGE = 2

#       def index
#         @page = params.fetch(:page, 0).to_i
#         @page = 0 if @page.negative? || @page > (Post.count / POSTS_PER_PAGE)

#         # @user = User.find(params[:user_id])
#         @users = current_user
#         @posts = @user.posts.includes(:comments)
#         @all_posts = Post.where(user: params[:user_id])
#         # @comments = Comment.where(post_id: params[:user_id])
#         @comments = Comment.includes([:user]).where(post_id: params[:user_id])
#       end

#       def show
#         @post = Post.find(params[:id])
#         # @user = User.find(params[:user_id])
#         @users = current_user
#         # @comments = Comment.where(post_id: params[:id])
#         @comments = Comment.includes([:user]).where(post_id: params[:id])
#       end

#       def new
#         @post = Post.new
#         render :new
#       end

#       def create
#         @post = Post.new(params.require(:post).permit(:title, :text))
#         @post.user = current_user

#         if @post.save
#           flash[:success] = 'New Post saved successfully!'
#           redirect_to user_posts_path(current_user)
#         else
#           flash.now[:error] = 'Post failed..'
#           render :new
#         end
#       end

#       def destroy
#         @user = User.find(params[:user_id])
#         @post = Post.find(params[:id])
#         @comments = @post.comments
#         @likes = @post.likes
#         @likes.destroy_all
#         @comments.destroy_all
#         @post.destroy
#         @user.decrement(:posts_counter)
#         @user.save

#         redirect_to user_posts_path(current_user)
#       end
#     end
#   end
# end

module Api
  module V1
    class PostsController < ApplicationController
      before_action :require_login
      def index
        # posts = Post.where(user: params[:user_id]).order('created_at DESC')
        posts = Post.includes([:user]).order('created_at DESC')

        p params[:id]
        render json: PostRepresenter.new(posts).as_json
      end
    end
  end
end

app/views/posts/index.html.erb
<div class='user_body'>
  <%=render partial: 'partials/user_card', locals: { user: @user }%>
  
  <div class='top_post_list'>
    <%@all_posts.each_with_index do |post, index|%>
    <%=render partial: 'partials/post_card', locals: { post: post, index: index, user: @user }%> 
    <%post.recent_comments.each do |comment|%>
        <div><%="#{comment.user.name}: #{comment.text}"%></div>
      <%end%>
    <%end%>

    <%if @user.posts_counter == 0%>
      <div>No posts to show</div>
    <%end%>
    
    <button type='button'><%= link_to "Create new post", new_user_post_path(@user) %></button>

    <div class="pagination">
      <div class="btn">
        <%=link_to "Previous Page", user_posts_path(@user, page: @page - 1)%>
      </div>
      <p><%=@page + 1%></p>
      <div class="btn">
        <%=link_to "Next Page", user_posts_path(@user, page: @page + 1)%>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<br>
<%= render partial: "partials/form", locals: {post: @post}%>

app/views/posts/show.html.erb
<div class="post_body">
  <%=render partial: 'partials/post_expanded', locals: { post:@post, user: @user }%>
  <%= form_with url: "/users/#{@user.id}/posts/#{@post.id}/likes" do |like|%>
    <%=like.submit "Like Post"%>
    <%if can? :manage, @post%>
    <%end%>
  <% end %>
  <div class="post_comments">
    <div>Comments</div>
      <%@comments.each do |comment|%>
        <div><%="#{comment.user.name}: #{comment.text}"%></div>
        <%if can? :manage, comment%>
          <%= button_to "Delete Comment", user_post_comment_path(comment.user_id, comment.post_id, comment.id), method: :delete %>
        <%end%>
      <%end%>
  </div>

<div>
  <button type='button'><%= link_to "Comment", new_user_post_comment_path(@user, @post) %></button>
</div>
<%if can? :manage, @post%>
<%= button_to "Delete Post", "/users/#{@user.id}/posts/#{@post.id}", method: :delete %>
<%end%>